In [1]:
import numpy as np
import numpy.linalg as la
import scipy.sparse as sm

In [2]:
A = np.array([[0,3,0],[7,0,0],[0,0,1]])
print(np.dot(A,A))
A

[[21  0  0]
 [ 0 21  0]
 [ 0  0  1]]


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [5]:
B = sm.csc_matrix([ [0,3,0],[7,0,0],[0,0,1]])
#este comando las ordena por columnas
print(B)
B

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (1, 0)	7
  (0, 1)	3
  (2, 2)	1


<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>

In [6]:
B = sm.csr_matrix([ [0,3,0],[7,0,0],[0,0,1]])
#este comando las ordena por renglones
print(B)
B

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 1)	3
  (1, 0)	7
  (2, 2)	1


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>